sudo: required
language: node_js
services:
- docker
before_install:
- docker-compose build .
script:
- docker run -e CI=true netguru_node npm run test
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: "uOPOPZ9tqp52s7J24eM8WuM4vv9hlOtv1WuhZuJNNlDvfDx1kCur/2/FDdP0YxLdvMINvfOQJTEiQsXNxefh7zMhntG+IV/bq9Kh5OiykVWSOJ9Wz7Yv76EzM7n5LasfAQ9CwnF6KYdc/ZgJ8oVPE74IW4Usn6GH3cj7qnNMoPxrzMXNEyqgja2oxJlaZo3vHoKwi7txLUmo6MzPwtgNaWve19PKbb+AsJbK+bLDmTAEhUHYSDD6DkNRvB/wYp2X2S6UcDyT13gRbVDyonyfWqJINelhi6bGUSJtvtD+oCyR1yX/th+QmyFIGUoSal0J1NGLTEaBMjJvBRQRq3JwGqC2Q41++hdQ0vYuTQopL6HcY4zCVnnevTT2A2HMc9byWztgqPougx54bAhKumBZDmQbySjPOGwGGrxlBvQO/78/Yl5YhiiF1jkRK+iSRVzyt4L+z5RNe1EVZPG8XLhQ8kqElbqaDSB6KAZw4sBOgxwQkpnUPi6SLobosVm7sUMw3T7ri2jGQUNDmpiAlpM67yFjNhc8fdoQ1N6I4Rjnf1xEWrGPYXL+GCn7HXAy+tU3poKaR2BIDKAhV08eiqTdaPilScVub8FE0hfuyJ9vCcelKlZPo4jowMkKswsreiY2ttWvK1rx8rF6A3gisiyp2jWDjQuSI5ykLsMdbJPpgHg="
  app:
    master: netguru-simple-staging-api
    production: netguru-simple-prod-api
